name: CICDJAVA

on:  
  push:  
    branches-ignore: [ master, develop, staging ]    
  pull_request:  
    branches: [ develop, staging ]
    types:  [ opened, closed ]
  release:
    types: [ created ]
  
jobs:
  Build:
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo ${{ github.release.target_commitish }} ${{ github.event_name }} - ${{ github.base_ref }} - ${{ github.ref }} - ${{ github.event.pull_request.merged }} - ${{ github.event.action }} $GITHUB_CONTEXT - Compile Step..
        
  Testing:  
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v2

      - name: Unit Testing
        run: echo Unit testing...

  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request' && github.ref == 'develop' && github.event.pull_request.merged
    needs: [Build, Testing]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://someweb.com'
    steps:
      - name: Upload to code artifactory
        run: echo Uploading snapshot artifactory....
      - name: Code Deploy
        run: echo Deploying Dev....   
    
  DeployPreproduction:
    name: Deploy to Preproduction 
    if: github.event_name == 'pull_request' && github.ref == 'staging' && github.event.pull_request.merged
    needs: [Build, Testing]
    runs-on: ubuntu-latest
    environment: 
      name: Preproduction
      url: 'http://someweb.com'
    steps:
      - name: Getting snapshot artifact from code artifactory
        run: echo Getting snapshot artifact from code artifactory....
      - name: Upload to code artifactory (Release)
        run: echo Uploading release artifactory ....
      - name: Code Deploy
        run: echo Deploying Preproduction...!
  
  TaggingDeployPreproduction:
    needs: [DeployPreproduction]    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 

      - name: Tagging to Staging Branch        
        run: |
            deploymentTag=$(date +'v%Y.%m.%d.%H%M')
            echo "$GITHUB_CONTEXT"
            echo "Tag Id: $deploymentTag"
            messageTag="Tag $deploymentTag created automatically due to the merge request to staging branch with details: Commit hash: ${{ github.sha }} Username: ${{ github.actor }}."
            echo "Message Tag: $messageTag"            
            git config --global user.email ""
            git config --global user.name "${{ github.actor }}"
            git tag -a $deploymentTag -m "$messageTag"
            echo "Tag created: $deploymentTag into staging branch."
            git push --tags --progress
            echo "Push created with tag: $deploymentTag"
            
  DeployProduction:
    name: Deploy to Production 
    if: github.event_name == 'release'
    needs: [Build, Testing]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://someweb.com'
    steps:
      - name: Getting release artifact from code artifactory
        run: echo Getting release artifact from code artifactory....
      - name: Code Deploy
        run: echo Deploying Production...!

  HotFixProduction:
    name: Deploy HotFix into Production 
    if: github.event_name == 'release' && contains('refs/tags/HotFix_', github.ref)
    needs: [Build, Testing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Code
        run: echo Compile code..
      - name: Unit Testing 
        run: echo Unit Testing ..
      - name: Create and upload release artifact
        run: echo Creating and upload release artifact....
      - name: Code Deploy
        run: echo Deploying Production...!
